steps:
  - name: scaler
    class: sklearn.preprocessing.StandardScaler
    parameters:
      with_mean: true
      with_std: true

  - name: classifier
    class: sklearn.ensemble.RandomForestClassifier
    parameters:
      n_estimators: 100
      max_depth: 10
      min_samples_split: 5
      min_samples_leaf: 2
      random_state: 42
      n_jobs: -1 